import turtle
turtle.shape('turtle')
turtle.speed(3)
turtle.begin_fill()
turtle.fillcolor('black')
for i in range(0,3):
    turtle.fd(100)
    turtle.right(90)
turtle.fd(100)
turtle.end_fill()
turtle.rt(90)
turtle.fd(200)
turtle.begin_fill()
turtle.fillcolor('black')
for i in range(0,3):
    turtle.fd(100)
    turtle.right(90)
turtle.fd(100)
turtle.end_fill()
turtle.penup()
turtle.goto(0,-200)
turtle.pendown()
turtle.fd(100)
turtle.rt(90)
turtle.fd(100)
turtle.rt(90)
turtle.fd(100)
turtle.lt(90)
turtle.begin_fill()
turtle.fillcolor('black')
for i in range(0,3):
    turtle.fd(100)
    turtle.lt(90)
turtle.fd(100)
turtle.end_fill()
turtle.lt(90)
turtle.fd(200)
turtle.lt(90)
turtle.fd(100)
turtle.lt(90)
turtle.fd(100)
turtle.penup()
turtle.goto(0,-200)
turtle.pendown()
turtle.rt(180)
turtle.begin_fill()
turtle.fillcolor('black')
for i in range(0,3):
    turtle.fd(100)
    turtle.right(90)
turtle.fd(100)
turtle.end_fill()
turtle.rt(90)
turtle.fd(200)
turtle.rt(90)
turtle.fd(100)
turtle.rt(90)
turtle.fd(100)
turtle.rt(90)
turtle.fd(100)
turtle.rt(90)
turtle.fd(100)
turtle.begin_fill()
turtle.fillcolor('black')
for i in range(0,3):
    turtle.fd(100)
    turtle.right(90)
turtle.fd(100)
turtle.end_fill()


a=float(input('价格:'))
i=int(a / 1.9)
print(i)




